# This will automatically build and deploy roverdriverweb to gh-pages upon push to main

name: Autodeploy

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd roverdriverweb
          pwd
          npm i

      - name: Build
        run: |
          cd roverdriverweb
          pwd
          grep -rl 'BUILD_DATE' ./src --exclude-dir=.git | xargs sed -i "s/BUILD_DATE/$(date)/g"
          grep -rl 'BUILD_HASH' ./src --exclude-dir=.git | xargs sed -i "s/BUILD_HASH/$(git rev-parse --short HEAD)/g"
          npm run build

      - name: Deploy
        run: |
          pwd
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add roverdriverweb/build -f
          git commit -m "Autodeploy by Github Actions"
          git subtree split --prefix roverdriverweb/build -b gh-pages
          git status
          git push -f origin gh-pages:gh-pages

      # git checkout gh-pages -f
      # git pull -s recursive -X ours --rebase origin gh-pages
      # git push origin gh-pages:gh-pages
