# This is a basic workflow to help you get started with Actions

name: CI GitHub Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ rover-web ]
  pull_request:
    branches: [ rover-web ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
                ref: rover-web
      - name: Hello
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Switch directory
        run: |
          cd $GITHUB_WORKSPACE
          cd roverdriverweb
          pwd
          ls
    
      - name: Install dependencies
        run: |
          cd roverdriverweb
          pwd
          npm i

      - name: Build
        run: |
          cd roverdriverweb
          pwd
          npm run build
          
      - name: Deploy
        run: |
          pwd
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree build add --all
          git commit -m "Autodeploy by Github Actions"
          git push origin HEAD:gh-pages --force
